### ISSUE TITLE
error: metadata-generation-failed

### ISSUE THREAD

**Issue by brianmcdonald** [Sjlver/yxf#1]
Dear Jonas,

Thank you for making this wonderful tool.
I am getting the following message when I try to install on Windows 10. 
Is there a problem with the package? 

`  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.`

**Comment by Sjlver** [comment]
Hi. I'm happy that you consider using yxf.

The "error: metadata-genenration failed" can occur for several reasons:

- Having an outdated version of pip and setuptools.
- Having a Python version that is not supported by the package you're trying to install. (Are you using Python 3?)
- Misspelling the name of the package.
- Errors related to dependencies.

Could you retry? If it still fails, please put the *complete* output here, along with the command that you have tried. It might also help to run pip with the `--verbose` option.

**Comment by brianmcdonald** [comment]
Yes. I must have misspelled it. It installed fine when I tried it today.
Thanks again. I'm looking forward to having xlsforms in a format that can be version controlled.
