### ISSUE TITLE
Error '_get_unpatched' from 'setuptools.dist'

### ISSUE THREAD

**Issue by rklausen12** [Sjlver/yxf#2]
Hi all,

I'm a data manager. I'm trying to install yxf on Windows. I'm getting this error:

C:\Windows\System32>python -m pip install yxf
Collecting yxf
  Using cached yxf-0.3.0-py3-none-any.whl (9.1 kB)
Collecting grapefruit (from yxf)
  Using cached grapefruit-0.1a4.tar.gz (13 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py:498: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'requires-dist' will not be supported in future
              versions. Please use the underscore name 'requires_dist' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
        dist.fetch_build_eggs(dist.setup_requires)
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-install-gndvqsgk\grapefruit_b46a4ba7f1bc48c9a649100bba33b205\setup.py", line 24, in <module>
          setup(
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
                                       ^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 303, in __init__
          _Distribution.__init__(self, dist_attrs)
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 680, in finalize_options
          ep(self)
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 700, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "c:\users\user\appdata\local\temp\pip-install-gndvqsgk\grapefruit_b46a4ba7f1bc48c9a649100bba33b205\.eggs\d2to1-0.2.12.post1-py3.12.egg\d2to1\core.py", line 30, in d2to1
          from setuptools.dist import _get_unpatched
      ImportError: cannot import name '_get_unpatched' from 'setuptools.dist' (C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py). Did you mean: 'get_unpatched'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I don't know what to do.

Thanks for the help.

**Comment by rklausen12** [comment]
I'm using 
C:\Windows\System32>python --version
Python 3.12.0

C:\Windows\System32>pip --version
pip 23.2.1 from C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip (python 3.12)

**Comment by Sjlver** [comment]
Hi, thanks for reporting this! It looks like there's a problem while installing `grapefruit`, one of the libraries that `yxf` depends on. Sorry about that... multiple people had problems with it; I'll try to find an alternative.

In the meantime: Some people were able to fix installation errors by running `pip install wheel` before installing yxf. Could you try that and let me know if it works?

**Comment by Sjlver** [comment]
Hi again,

I've just published version 0.4.0, which no longer depends on `grapefruit`. This one should install without problems, just using `pip install yxf`.

Please let me know if this works. If you have any other feedback about yxf, don't hesitate to reach out.

**Comment by rklausen12** [comment]
It works perfectly.
Thank you.
