### ISSUE TITLE
Any starter file?

### ISSUE THREAD

**Issue by hamzakat** [Sjlver/yxf#3]
Hello @Sjlver 

Thanks for making this package. It's really an awesome idea to implement forms as code!
I tried to convert a .yaml file but I faced a lot of errors. It seems like my file is not compatible with the tool. I tried the format you provided in the screenshot but it seems there is something missing.
Could you please provide a guide on the format in the README file or maybe an example .yaml file so we can use it as a boilerplate?

**Comment by Sjlver** [comment]
Hi @hamzakat,

I'm happy to hear that you're interested in yxf.

The easiest way to get a YAML file is to take an existing xlsform file (that is, an Excel table with a `survey`, `choices`, and `settings` sheet). Then you can use yxf to convert this file to YAML. If that doesn't work, let me know. Ideally, include the error message that yxf prints.

Let me know if that helped!

**Comment by hamzakat** [comment]
Yup, that works!

Error messages were appearing because I wasn't adding the `yxf:` section properly.
